[package]
name = "hemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
script = "script/build.rs"

[dependencies]
rustyline = "7.1.0"
lazy_static = "1.4.0"
libc = "0.2.144"
log = "0.4.17"
env_logger = "0.10.0"
atoi = "2.0.0"
ansi_term = "0.12.1"
clap = { version = "4.3.11", features = ["derive"] }
regex = "1.9.0"
eval = "0.4.3"
qemu_difftest = {path = "../qemu-diff"}
