[package]
name = "hemu"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
verilated = { path = "./verilator/verilated" }
verilated-module = { path = "./verilator/verilated-module" }
clap = { version = "4.3.11", features = ["derive"] }
anyhow = "1.0.80"

[build-dependencies]
verilator = { path = "./verilator/verilator", features = ["gen", "module"] }
