[package]
name = "hemu"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "7.1.0"
lazy_static = "1.4.0"
libc = "0.2.144"
log = "0.4.17"
env_logger = "0.10.0"
atoi = "2.0.0"
ansi_term = "0.12.1"
clap = { version = "4.3.11", features = ["derive"] }
regex = "1.9.0"
eval = "0.4.3"
anyhow = "1.0.80"
rvemu = "0.0.11"
