name: test
on: push
jobs:
  am-test:
    name: am-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test am-tests
  riscv-test-rv64ui:
    name: riscv-test-rv64ui
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-rv64ui
  riscv-test-rv64mi:
    name: riscv-test-rv64mi
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-rv64mi
  riscv-test-rv64si:
    name: riscv-test-rv64si
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-rv64si
  riscv-test-rv64um:
    name: riscv-test-rv64um
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-rv64um
  riscv-test-rv64ua:
    name: riscv-test-rv64ua
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-rv64ua