name: test
on: push
jobs:
  am-test:
    name: am-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test am-tests
  riscv-test:
    name: riscv-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests