name: test
on: push
jobs:
  am-test:
    name: am-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test am-tests
  riscv-test-p:
    name: riscv-test-p
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-p
  riscv-test-v:
    name: riscv-test-v
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: test
      run: cargo test --test riscv-tests-v